name: Build and Deploy Liferay Modules

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Clean, Build, and Deploy the Liferay modules
      - name: Clean, Build, and Deploy Liferay modules
        run: |
          ./gradlew clean build deploy  # Clean, build, and deploy using the Gradle wrapper

      # Step 3: Move JAR files to Liferay deploy folder
      - name: Move JAR files to Liferay deploy folder
        shell: pwsh  # Use PowerShell
        run: |
          $liferayDeployDir = "${{ vars.LIFERAY_HOME }}\deploy"
          Get-ChildItem -Path "modules\*\build\libs\*.jar" | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination $liferayDeployDir
          }

      # Step 4: (Optional) Verify Deployment
      - name: Verify Deployment
        run: |
          echo "Deployment completed. JAR files moved to the deploy folder."
