name: Build and Deploy Liferay Modules

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the pipeline on

jobs:
  build:
    runs-on: ubuntu-latest  # Or use self-hosted runner if needed
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Liferay DXP typically uses JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Set up Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.x  # Adjust according to your Liferay version

      # Step 4: Build the Liferay workspace
      - name: Build Liferay modules
        run: ./gradlew clean build

      # Step 5: Deploy to local Liferay bundle
      - name: Deploy to local Liferay
        run: |
          ./gradlew deploy
        env:
          LIFERAY_HOME: ${{ vars.LIFERAY_HOME }}
